name: Build

on:
  push:
    # tags:
    #   - "v*"
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Go environment
        uses: actions/setup-go@v5.2.0
        with:
          go-version: 1.23.2

      - name: Install dependencies
        run: go mod download

      - name: Build
        run: make build