name: Create release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Go environment
        uses: actions/setup-go@v5.2.0
        with:
          go-version: 1.23.2

      - name: Install dependencies
        run: go mod download

      - name: Build
        run: make build

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
              ./bin/temperature-exporter \
              --repo="$GITHUB_REPOSITORY" \
              --title="${tag#v}" \
              --generate-notes